// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4MtnfQYt73LP27MkG6d5nXshjO8t5ym8',
    appId: '1:602643092439:web:9dcb85e85ec9869ceff192',
    messagingSenderId: '602643092439',
    projectId: 'facturasya-73d2f',
    authDomain: 'facturasya-73d2f.firebaseapp.com',
    storageBucket: 'facturasya-73d2f.appspot.com',
    measurementId: 'G-5Y36319QGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUbDnJSRVM0lXuSqhqHv0FfBiIHSTsg2Q',
    appId: '1:602643092439:android:58d825810aa09b6aeff192',
    messagingSenderId: '602643092439',
    projectId: 'facturasya-73d2f',
    storageBucket: 'facturasya-73d2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjC07TAvfQDNGTwzTxPUb2PlIbTPxVgNA',
    appId: '1:602643092439:ios:45bfd07c1fa90fb8eff192',
    messagingSenderId: '602643092439',
    projectId: 'facturasya-73d2f',
    storageBucket: 'facturasya-73d2f.appspot.com',
    androidClientId: '602643092439-5djro96cgfj90ecv5giof3lfp00kbhrb.apps.googleusercontent.com',
    iosClientId: '602643092439-5l3jc7igaunba85f25gas4prj4p7of63.apps.googleusercontent.com',
    iosBundleId: 'com.example.engineering',
  );
}
